### ISSUE TITLE
Issues with demo page

### ISSUE THREAD

**Issue by strarsis** [codrops/Arctext#5]
Because the demo uses the JavaScript files over non-HTTPS, 
the demo doesn't work until the external JavaScript files have been explicitly allowed in Chrome.

**Comment by crnacura** [comment]
Thank you very much for reporting this. All file inclusions are fixed now and the demo should be working fine.

**Comment by strarsis** [comment]
@crnacura: Yes, it works now - I had to do a hard-refresh (browser cache) of the page.
